FROM scratch

ENV SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
ENV SSL_CERT_DIR=/etc/ssl/certs

COPY ./target/x86_64-unknown-linux-musl/release/esi-markets /esi-markets
COPY ./Rocket.toml /Rocket.toml

EXPOSE 8000

CMD ["/esi-markets"]